name: BIQU_B1_SKR_1.4

on:
  push:
    branches:
      - master
    paths:
      - 'Firmware/Configuration/BIQU/B1/SKR_1.4/**.h'
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build_and_push:
    name: Compile and Push Firmware
    runs-on: ubuntu-latest
    env:
      BOARD: LPC1768

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Compile firmware
        run: |
          docker run \
            -u root:root \
            -e BOARD \
            -e USE_TAG=2.1.2.1 \
            -v $(pwd)/Firmware/Builds/BIQU/B1/SKR_1.4:/home/platformio/build \
            -v $(pwd)/Firmware/Configuration/BIQU/B1/SKR_1.4:/home/platformio/CustomConfiguration \
            frealmyr/marlin-build:latest

      - name: Push firmware
        run: |
          git config --global user.name "alienboyxp"
          git config --global user.email "jrodriguez@qitec.net"
          git pull origin master --ff-only
          git add .
          git commit -m "Compiled firmware"
          git push "https://${{ github.actor }}:${{ secrets.COMMIT_TOKEN }}@github.com/${{ github.repository }}.git"