name: CI - Update Gists from Repository
on:
    push:
      branches:
        - master
      paths:
        - 'readme.md'
permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code for marlin_auto_builder_3dwork
            uses: actions/checkout@v3
        
        - name: Creating start_print.cfg Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
            token: ${{ secrets.COMMIT_TOKEN }}
            gist_id: 07b5a603f9becbe484182f8c5dc25b52
            file_path: readme.md
            file_type: binary