name: Kingroon_KP3S

on:
  push:
    branches:
      - master
    paths:
      - 'Firmware/Configuration/Kingroon/KP3S/**.h'
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build_and_push:
    name: Compile and Push Firmware
    runs-on: ubuntu-latest
    env:
      BOARD: mks_robin_nano_v1v2

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Compile firmware
        run: |
          docker run \
            -u root:root \
            -e BOARD \
            -e USE_TAG=2.1.2.1 \
            -v $(pwd)/Firmware/Builds/Kingroon/KP3S/2_1_2_1:/home/platformio/build \
            -v $(pwd)/Firmware/Configuration/Kingroon/KP3S:/home/platformio/CustomConfiguration \
            frealmyr/marlin-build:latest

      - name: Push firmware
        run: |
          git config --global user.name "JJR Bot"
          git config --global user.email "jrodriguez@qitec.net"
          git pull origin master --ff-only
          git add .
          git commit -m "Compiled firmware"
          git push "https://${{ github.actor }}:${{ secrets.COMMIT_TOKEN }}@github.com/${{ github.repository }}.git"